/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopapplication;

import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;

/**
 *
 * @author Nagy-Zsugya Bálint
 */
public final class AddToCartJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddToCartJFrame
     */
    public AddToCartJFrame() {
        initComponents();
        increaseAmount();
        decreaseAmount();
    }
    
    public AddToCartJFrame(Cart mainCart, Ware selectedWare, Storage mainStorage, JTable waresTable) {
        initComponents();
        increaseAmount();
        decreaseAmount();
        addToCartByButton(mainCart, selectedWare, mainStorage, waresTable);
    }
    
    public void increaseAmount(){
        increaseButton.addActionListener((ActionEvent e) -> {
            int increasedAmount = Integer.parseInt(amountTextField.getText()) + 1;
            amountTextField.setText(String.valueOf(increasedAmount));
        });
    }
    
    public void decreaseAmount(){
        decreaseButton.addActionListener((ActionEvent e) -> {
            if(Integer.parseInt(amountTextField.getText()) - 1 > 0){
            int decreasedAmount = Integer.parseInt(amountTextField.getText()) - 1;
            amountTextField.setText(String.valueOf(decreasedAmount));
            } else {
                System.out.println("The amount can't be less than 0!!");
            }
        });
    }
    
    public void addToCartByButton(Cart mainCart, Ware selectedWare, Storage mainStorage, JTable waresTable){
        addButton.addActionListener((ActionEvent e) -> {
        int amount = Integer.parseInt(amountTextField.getText());
        if(amount <= selectedWare.getQuantity()){
        Ware buyWare = new Ware(selectedWare.getName(), selectedWare.getPrice(), selectedWare.getCategory(), amount);
        mainCart.addToCart(buyWare);
        File cart = new File("cart.txt");
            try {
                FileWriter cartWriter = new FileWriter(cart);
                if(!mainCart.getCart().isEmpty()){
                for(int i = 0; i < mainCart.getCart().size(); i++){
                    cartWriter.write(mainCart.getCart().get(i).getName() + ";" + mainCart.getCart().get(i).getPrice() + ";" + mainCart.getCart().get(i).getCategory() + ";" + mainCart.getCart().get(i).getQuantity() + "\n");
                    }
                }
                cartWriter.close();
            } catch (IOException ex) {
                Logger.getLogger(AddToCartJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
                    System.out.println("Insufficient amount!");
        }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amountTextField = new javax.swing.JTextField();
        increaseButton = new javax.swing.JButton();
        decreaseButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        amountTextField.setEditable(false);
        amountTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        amountTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amountTextField.setText("1");

        increaseButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        increaseButton.setText("+");
        increaseButton.setMaximumSize(new java.awt.Dimension(41, 37));
        increaseButton.setMinimumSize(new java.awt.Dimension(41, 37));

        decreaseButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        decreaseButton.setText("-");

        addButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(decreaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(amountTextField))
                .addGap(18, 18, 18)
                .addComponent(increaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(increaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decreaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddToCartJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddToCartJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddToCartJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddToCartJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AddToCartJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField amountTextField;
    private javax.swing.JButton decreaseButton;
    private javax.swing.JButton increaseButton;
    // End of variables declaration//GEN-END:variables
}
